DROP DATABASE IF EXISTS techBlog;
CREATE DATABASE techBlog;
CREATE TABLE IF NOT EXISTS `Posts` (
 `id` INTEGER NOT NULL AUTO_INCREMENT,
 `title` VARCHAR(255) NOT NULL,
 `content` TEXT NOT NULL,
 `createdAt` DATETIME NOT NULL,
 `updatedAt` DATETIME NOT NULL,
 `userId` INTEGER,
 PRIMARY KEY (`id`),
 FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;